{% set name = "napari-J" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-J-{{ version }}.tar.gz
  sha256: bc11062b7a0704b6654c4af306639716bc232baf3ff8bb3053e05895c4fb4603

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - imageio-ffmpeg  # pip check
    - jpype1 >=1.2.1
    - jupyter_client
    - magicgui
    - matplotlib-base
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >={{ python_min }}
    - pyyaml
    - qtpy
    - scikit-image
    - vispy

test:
  imports:
    - napari_j
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MontpellierRessourcesImagerie/napari-J
  summary: A plugin to exchange data with FIJI and to use FIJI image analysis from napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
